version: '3'
services:
  webapp:
    restart: always
    build: .
    volumes:
      - .:/inet_b
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8888"
    ports:
      - "8000:8000"